general.live_config_reload = true
terminal.shell.program = "zellij"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
decorations_theme_variant = "Dark"
opacity = 0.98

[window.dimensions]
columns = 200
lines = 50

[window.padding]
x = 10
y = 10

[scrolling]
history = 10000
multiplier = 3

[font]
size = 10

[font.normal]
family = "MapleMonoNormalNLNF"
style = "Regular"

[font.bold]
family = "MapleMonoNormalNLNF"
style = "Bold"

[font.italic]
family = "MapleMonoNormalNLNF"
style = "Italic"

[font.bold_italic]
family = "MapleMonoNormalNLNF"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[colors.cursor]
text = "#1d2021"
cursor = "#fabd2f"

[colors.selection]
text = "#ebdbb2"
background = "#3c3836"

[colors.normal]
black   = "#1d2021"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[colors.dim]
black   = "#141617"
red     = "#9d0006"
green   = "#79740e"
yellow  = "#b57614"
blue    = "#076678"
magenta = "#8f3f71"
cyan    = "#427b58"
white   = "#928374"

[colors.search]
matches = { foreground = "#1d2021", background = "#d79921" }
focused_match = { foreground = "#1d2021", background = "#fabd2f" }

[colors.hints]
start = { foreground = "#d79921", background = "#1d2021" }
end   = { foreground = "#1d2021", background = "#d79921" }

[colors.vi_mode_cursor]
text = "#1d2021"
cursor = "#83a598"

[colors.line_indicator]
foreground = "#ebdbb2"
background = "#3c3836"

[colors.footer_bar]
background = "#282828"
foreground = "#ebdbb2"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
command = "xdg-open"
post_processing = true
mouse.enabled = true
binding = { key = "T", mods = "Control|Shift" }

[[hints.enabled]]
regex = "[0-9a-f]{12,128}|[a-f0-9]{7,8}"
action = "Copy"
binding = { key = "H", mods = "Control|Shift" }
