general.live_config_reload = true
terminal.shell.program = "zellij"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
decorations_theme_variant = "Dark"
opacity = 1

[window.dimensions]
columns = 200
lines = 50

[window.padding]
x = 10
y = 10

[scrolling]
history = 10000
multiplier = 3

[font]
size = 10

[font.normal]
family = "MapleMonoNormalNLNF"
style = "Regular"

[font.bold]
family = "MapleMonoNormalNLNF"
style = "Bold"

[font.italic]
family = "MapleMonoNormalNLNF"
style = "Italic"

[font.bold_italic]
family = "MapleMonoNormalNLNF"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#22272e"
foreground = "#adbac7"

[colors.cursor]
text = "#22272e"
cursor = "#dcbdfb"

[colors.selection]
text = "#adbac7"
background = "#6cb6ff"

[colors.normal]
black   = "#1c2128"
red     = "#f47067"
green   = "#57ab5a"
yellow  = "#f69d50"
blue    = "#6cb6ff"
magenta = "#dcbdfb"
cyan    = "#4EC9B0"
white   = "#adbac7"

[colors.bright]
black   = "#373e47"
red     = "#e5534b"
green   = "#347d39"
yellow  = "#e0823d"
blue    = "#539bf5"
magenta = "#8256d0"
cyan    = "#57ab5a"
white   = "#cdd9e5"

[colors.dim]
black   = "#22272e"
red     = "#ff938a"
green   = "#46954a"
yellow  = "#f69d50"
blue    = "#4184e4"
magenta = "#dcbdfb"
cyan    = "#4EC9B0"
white   = "#636e7b"

[colors.search]
matches = { foreground = "#22272e", background = "#f69d50" }
focused_match = { foreground = "#22272e", background = "#539bf5" }

[colors.hints]
start = { foreground = "#f69d50", background = "#22272e" }
end   = { foreground = "#22272e", background = "#f69d50" }

[colors.vi_mode_cursor]
text = "#22272e"
cursor = "#539bf5"

[colors.line_indicator]
foreground = "#adbac7"
background = "#373e47"

[colors.footer_bar]
background = "#2d333b"
foreground = "#adbac7"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
command = "xdg-open"
post_processing = true
mouse.enabled = true
binding = { key = "T", mods = "Control|Shift" }

[[hints.enabled]]
regex = "[0-9a-f]{12,128}|[a-f0-9]{7,8}"
action = "Copy"
binding = { key = "H", mods = "Control|Shift" }
